isomerpages/moe-geylangmtdpri

_about-us/School Bus.md
_about-us/School Rules and Regulations.md
_our-partners/Family Matters@School.md

Approval, pls

---

pages/Announcements.md

Approval pls

---

_about-us/Principal's Message.md
_useful-links/2023 Gallery.md

Mostly are Gallery updates. Thank you.

For your Approval pls.

---

_about-us/Our People/Board of Management.md
_about-us/Our People/School Management Team.md

Some changes to the Board of management & Shcool Mgt Team pages.
Thank you.

For your approval, pls.

---

_about-us/Our People/Board of Management.md
_about-us/Our People/School Management Team.md

Slight amendment in name. Thank you

For your approval

---

_about-us/Our People/Board of Management.md
_about-us/School Rules and Regulations.md

For the changes done by ISOEMR.
Thank you

For your approval, pls

---

_about-us/Our People/School Management Team.md

Amended Ryna's email. Thank you

Approval pls.

---

_about-us/Our People/School Management Team.md

For your approval pls

---

_useful-links/For Students & Parents.md

P1 Student Hub

---

_about-us/School Bus.md
_useful-links/For Students & Parents.md

Change of School Bus email address

---

index.md
pages/Announcements.md

Remove GO Under Renovation in Home and Announcements Pages

---

_about-us/Our People/School Management Team.md

Dear Mr Wan / Mildred,
Please assist to approve.
Thank you.
Rgds
Hanitha

Changes to SMT page

---

_about-us/Our People/School Staff 2025.md

Updated Teacher's listings 

---

_about-us/Our People/School Staff 2025.md

Numerous updates

---

_about-us/Our People/School Staff 2025.md
_about-us/Principal's Message.md

2025 Principal's Message Updated

---

_useful-links/For Students & Parents.md

To be shared with and Internet QRCode

Link to 2025 Prefect Investiture eBrochure

---

_about-us/Our People/School Management Team.md

Update Kelly's error

---

_about-us/Our People/School Staff 2025.md

Update Yap Siew Hong's error email address

---

_about-us/Our People/School Staff 2025.md

Corrected Ms Ng Joo Siah's email

Update erronous email address

---

_co-curricular-activities/CCA Policy & Schedule.md

Update CCA Policy

---

_about-us/Our People/School Staff 2025.md

Updated Chris email

---

_about-us/Our People/School Staff 2025.md

Mdm Sarina request removal of her father's name, for privacy reasons

---

_co-curricular-activities/Visual and Performing Arts/Art & Crafts Club.md
_co-curricular-activities/Visual and Performing Arts/Guzheng Ensemble.md

Updated Guzheng and Art & Craft webpages

---

_curriculum/Aesthetics.md

Aesthetic Pages completed 

---

_about-us/Our People/School Staff 2025.md
_co-curricular-activities/Clubs & Societies/Environmental Science Club.md
_co-curricular-activities/Sports & Games/Track & Field.md
_co-curricular-activities/Visual and Performing Arts/Visual & Performing Arts.md
_co-curricular-activities/collection.yml

Corrected error to Amanda's email, pls approve

Updated Amanda's email

---

_about-us/Non Financial Information.md

Board Of Management Updated

---

_about-us/Non Financial Information.md

BOM Updated

---

_about-us/School Policy/Homework Policy.md

HOMEWORK POLICY

---

_achievements/2025.md
_achievements/2025/Student Achievements.md
_achievements/collection.yml

New 2025 Achievement Page

---

_about-us/Our People/School Staff 2025.md

Updated Staff List
